name: baseconvert
description: Convert any rational number from any (positive integer)
  base to any (positive integer) base. Output numbers as List or String.
version: 1.0.2
homepage: https://hiddenquarter.com
repository: https://github.com/randomdude583/baseconvert

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:


dev_dependencies:
  test: ^1.17.7
